# Generated by Django 3.2.5 on 2021-07-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mulima_app', '0002_auto_20210706_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, upload_to='mulima_app/static/mulima_app/images'),
        ),
    ]
